### ISSUE TITLE
Implémenter les champs de statuts pour les membres

### ISSUE THREAD

**Issue by ozwin** [sysmoh/intranetBS#1]
Bouton pour le mettre en pause.
Il est grisé dans l'unité
Il ne reçoit pas de courrier

**Comment by nuffer** [comment]
c'est quoi la "pause" ?

**Comment by ozwin** [comment]
si un gars part à l'étranger, ou arrête pendant un temps fixe. 
C'est demandé par le new SG

**Comment by nuffer** [comment]
cela dit, si il part alors il sort des attribution et voila!! quand il revient on lui file une attribution.

D'ailleurs, je lance ici le débat sur le "statut" des membres...ca parait etre une redondance. Il suffit de voir  ses attribution actuelle.

Le seul interet de cette propriété serait un truc du grenre "on a recu l'inscription papier au secretariat"

**Comment by ozwin** [comment]
A mon avis c'est toujours utile. Ça ne doit être modifié que par le SG. Ça permet de savoir que l'inscription a été retournée (et afficher un message sur les membres qui n'ont pas rendu l'inscription.

C'est aussi bien de savoir pour quels personnes on a reçu une démission. Pas que ce soit juste un CP qui clos une attribution et que la personne s'évanouisse dans les limbes du netbs. Il y aura parfois des délai entre le moment ou une attribution est close et la suivante ouverte, on veut retrouver ces personnes facilement.

ça optimisera aussi les performance. Le moteur de recherche peut se focaliser sur les membres "en attente" ou "inscrits" sans devoir faire mille requêtes en plus pour connaitre les attributions et leur statut.

**Comment by nuffer** [comment]
Donc on doit faire une liste des statuts possible:

- en attente
- inscrit
-en pause
-désincrit
-décédé :-)

**Comment by ozwin** [comment]
oui

**Comment by nuffer** [comment]
@ozwin on parlé de ca y quelque jours...manifestement c'est pas la première fois qu'on a ce débat

**Comment by ozwin** [comment]
Haha non, pour rappel la nouvelle version :

Membre
- Date Inscription
- Date Désinscription
- Bool Décédé

Pas de "en attente", il s'agit soit d'un membre qui n'a pas de date d'inscription.

Pour la "Pause", je propose le report en v2 après feed-back des end users et après ça on verra si il faut mettre ça sur le membre ou sur les attributions.
