### ISSUE TITLE
Restructurer les vues : fournir des vues types pour chaque Type

### ISSUE THREAD

**Issue by ozwin** [sysmoh/intranetBS#11]

**Comment by nuffer** [comment]
J'ai commencé à faire ca avec les adresse / contact / telelphone / Email! 

est-ce que ca joue comme j'ai fais?

**Comment by nuffer** [comment]
Je propose queque regle de nomenclature pour les fichier twig...

Dans App/resources/views...

chaque dossier doit parler par sont nom...

Ensuite chaque fichier:
- si c'est une page: page_lenomdelapage.html.twig
-si c'est un fichier qui sera inclu dans une page, alors on est libre?!

**Comment by nuffer** [comment]
Je m'en suis occupé! il va falloir encore reglé les quelque bugs à cause de la migration des vue de /app a /appbundle:resources
