### ISSUE TITLE
Mettre une liste de fonctions possibles dans les types de groupes

### ISSUE THREAD

**Issue by ozwin** [sysmoh/intranetBS#13]
Ajouter aussi un label pour les types de groupe (pat. gars et pat. fille = "Patrouille")

**Comment by nuffer** [comment]
Yep!

Donc j'ai modifier la class Type (de groupe) qui a donc une fonctions chefs mais aussi une liste de fonctions possible dans les membre du groupe. Comme-ci dessous:

class Type
{
 ...
    private $nom;

    private $fonctionChef;

    private $fonctions;
...
}

Maintenant on a eu un débat sur comment faire que un type "patrouillle" soit en faite une "sizaine" en 1er Branche et une "patrouille" en deuxieme branche.

Le résultat de ce débat c'était de faire une sorte de table de traduction...un truc compliqué...

J'ai trouvé une solution bien plus simple qui répond au 3 critères qui nous paraissait important:

1) Un nomenclature adapté a chaque groupe (sizaine vs patrouille)
2) Pouvoir identifier tout les CUs donc un moyen de savoir que un CM et un CT sont les deux des CUs
3) rester simple: pour rajouter un groupe, je choisi un type et hop...pas besoin de table de traduction etc...

!!!!!! ===> Ma solution:

On met des label sur les fonctions!!! Par exemple, la fonctions CT et la fonction CM on tout les deux le meme label "CU"...même systeme pour gars et fille qui aurons un label "Kids"....

Ensuite, on peut utiliser ses labels pour des recherche et des diffusion d'infos...

qu'en pensez vous?

**Comment by ozwin** [comment]
La différence par rapport à la solution d'avant est pas énorme. Effectivement l'implémentation est plus simple mais on perd en qualité du modèle. On se retrouve ici avec une redondance d'information. 

Cela s'illustre dans le cas ou on veut changer l'unité d'un CU par exemple, passer de troupe à meute (c'est hypothétique) : on devra changer deux informations (l'unité et la fonction).

Avec la version première, il suffisait de changer l'unité et le nom de la fonction était automatiquement traduit (puisque la traduction est retrouvée à travers le groupe).

Après c'est un cas de figure plutôt peu fréquent et dont le risque principal est juste une erreur d'affichage (si le reste du code se réfère toujours au "label"). Donc si tu la sens de faire la version de base, je dirai c'est mieux, sinon on peut aussi partir comme ça pour une première version.

**Comment by nuffer** [comment]
Re!

Ok alors je vais partir avec ma version de label….Effectivement, on pourras tjs faire l’autre version plus tard car ça change pas des masses le model et on risque pas de devoir faire de gros changement.

La solutions « label «  étant plus simple à implémenter…

**Comment by nuffer** [comment]
La question est colose avec le nouveaux model: Groupe=>model=>catégorie
