### ISSUE TITLE
la recherche ne marche tjs pas chez moi

### ISSUE THREAD

**Issue by nuffer** [sysmoh/intranetBS#18]
une idée de ou ca vient? j'ai juste fait un elastica populate...

**Comment by sysmoh** [comment]
perso je sais pas pour toi, mais j'ai pas mal galéré dans l'installation d'elastica http://www.elasticsearch.org/overview/elkdownloads/

**Comment by nuffer** [comment]
mais si j'arrive a populate c'est que elastica est bien installé non?

**Comment by sysmoh** [comment]
Le problème vient probablement de la restructuration. J'appelais des méthodes comme getAdressePrincipale qui marchent plus maintenant, donc il a des erreurs.

**Comment by nuffer** [comment]
dsl :-)

**Comment by ozwin** [comment]
chez moi ça marche, après tout à coup plus, après de nouveau.

**Comment by nuffer** [comment]
Yep!

alors j'ai corrigé les route pour que le petit javascript envoye la "recherche" à la fonction: 

- public function layoutSearchAction(Request $request)  => SearchController

si j'entre donc "Odette" dans le champ de recherche, j'obtiens:

- $pattern = *Odette*

Ensuite, je passe à la fonctions suivante:

- return $this->get('fos_elastica.finder.search.membre')->find($pattern);

Mais j'obtiens aucun resultats de recherche...des idées?? (et oui j'ai fait un: fos:elastica:populate)

**Comment by ozwin** [comment]
La recherche fonctionne bien tant que elastica fonctionne, donc je clos l'issue
