### ISSUE TITLE
Question sur la memory limit de php...

### ISSUE THREAD

**Issue by nuffer** [sysmoh/intranetBS#23]
Lorsque je fais ca: ini_set('memory_limit', '-1'); //avoid memory limit exception!!!

Je supprime la limite de mémoire...Ma question:

Qu'elle est la portée de cette commande? la requete? la session? tout le serveur?

**Comment by ozwin** [comment]
Du [manuel](http://php.net/manual/fr/function.ini-set.php)
> string ini_set ( string $varname , string $newvalue )

> Change la valeur de l'option de configuration varname et lui donne celle de newvalue. La valeur de l'option de configuration sera modifiée durant toute l'exécution du script et pour ce script spécifiquement. Elle reprendra sa valeur par défaut dès la fin du script.

**Comment by nuffer** [comment]
Donc par script, on entend une requete?

**Comment by ozwin** [comment]
Oui

**Comment by nuffer** [comment]
top Merci

**Comment by ozwin** [comment]
Genre il fait un processus pour ta requête, change la limite dans ce processus et détruit le processus après la réponse envoyée.
