### ISSUE TITLE
Attribut "Nom" pour les membres

### ISSUE THREAD

**Issue by nuffer** [sysmoh/intranetBS#28]
Est-ce qu'on met en place un champ nom dans l'entité "Personne" car il se peut que les membres autant que les geniteur n'aie pas le meme nom de famille??!!

**Comment by nuffer** [comment]
@ozwin : qu'en pense tu?

**Comment by ozwin** [comment]
En soit oui, mais il faut pas qu'on l'affiche sur la page de modification, sinon tout le monde va laisser tomber les familles. Cela dit, est-ce que ça arrivera vraiment que deux membres de la même famille aient un nom différent ? Et si oui, ne vaut-il pas mieux faire deux familles ? Je pencherai pour cette dernière solution.

**Comment by nuffer** [comment]
Je suis d'accord!

Je close!
