### ISSUE TITLE
Créer un fichier avec tous les droits et la hiérarchie des droits

### ISSUE THREAD

**Issue by ozwin** [sysmoh/intranetBS#3]
Il sera complété au fur et à mesure qu'on a besoin de roles dans le code

**Comment by ozwin** [comment]
A mettre dans app/config

**Comment by nuffer** [comment]
Donc finalement les role sont dans la base de donnée en dure mais il existe un fichier pour crée la structure en dure. 
ce fichier est dans securitybundle et une commande va le lire pour crée la hierachie des role.

Pour moi on est ok avec cette issue! et vous?
