### ISSUE TITLE
Fix champ choice avec ajax_edit.html.twig

### ISSUE THREAD

**Issue by nuffer** [sysmoh/intranetBS#36]
Il y a un problème d'affichage une fois le champ choice modifier. tout les valeurs apparaise dans la div

**Comment by ozwin** [comment]
C'est toujours valable ça ? je comprend pas ce que c'est

**Comment by nuffer** [comment]
Aucune idée, faut checker…le plus simple c’est de regarder si champ sex homme/femme marche bien dans la page de memebre

Nicolas Uffer
+41 79/507.62.48
nicolas.uffer@gmail.com

**Comment by nuffer** [comment]
Y a toujours le bug sur le champ Envoi Facture en tout cas
