### ISSUE TITLE
Rendre le javascript mieux

### ISSUE THREAD

**Issue by sysmoh** [sysmoh/intranetBS#38]
A terme ce serait quand même cool que notre javascript soit mieux organisé que ce qu'on a maintenant, enfin je trouve. Dans le sens où y'a des appels ajax n'importe où, des trucs bizarre etc. Donc on a plusieurs solutions : 
- La première serait d'utiliser un framework frontend. Le plus populaire et performant pour l'instant c'est AngularJS développé par Google. Il est cool et balèze, mais super compliqué à apprendre (c'est genre le symfony2 du javascript avec moins de composants)
- On peut aussi utiliser un langage un peu moins yolo que je javascript (dans le sens où c'est vraiment le bordel ce langage, sérieux, depuis quand une fonction c'est un objet aussi ?), et qui compile vers le javascript. Pour ça on a le choix entre Dart (de google) et TypeScript (de microsoft). Ca peut nous permettre de mieux organiser notre code, et d'avoir des classes et tout bien foutues pour le front. 

C'est peut-être pas un problème pour l'instant, mais c'est déjà pas mal la croix et la bannière pour maintenir le javascript (et je suis le fautif principal parce que j'ai fait ça comme un cochon dès le début désolé :D)

Voila voila

https://angularjs.org/
https://www.dartlang.org/
http://www.typescriptlang.org/

**Comment by nuffer** [comment]
@ozwin je crois que tu t'en es occupé? est-ce qu'on close?

**Comment by ozwin** [comment]
On a pas mal parlé de ça et on avait fait quelques tests avec Angular2. Ca pourrait être très balèze et à mon avis la v3 sera faite comme ça, mais à l'heure actuelle ce n'est pas la priorité et une solution hybride est trop problématique. Pour l'instant on reste en jQuery pour taper du "modèle-vue" en mode moche.
