### ISSUE TITLE
Créer un service pour choper les droits enfants à partir des parents

### ISSUE THREAD

**Issue by ozwin** [sysmoh/intranetBS#4]

**Comment by nuffer** [comment]
Si j'ai bien compris, symfony fait ca tres bien tout seul....Guillaume, peut-tu confirmer? et on clos l'issue!

**Comment by ozwin** [comment]
Il fait pas que dans yaml ? 

Sinon qqun l'a fait pour nous sur [stackoverflow](http://stackoverflow.com/questions/11602337/how-to-change-role-hierarchy-storage-in-symfony2)
