### ISSUE TITLE
Créer le lien entre les fonctions et les droits

### ISSUE THREAD

**Issue by ozwin** [sysmoh/intranetBS#6]
Avec un formulaire qui permet de modifier dans l'interface d'admin

**Comment by nuffer** [comment]
Guillaume vient de le faire!!! trop bien!!

**Comment by nuffer** [comment]
Je propose qu'il ne soit pas possible d'ajouter une fonction dans cette onglet "matching" car on gere les fonctions possible dans la partie "structure"

**Comment by sysmoh** [comment]
Okok, perso je pensais ne garder que cette vue pour gérer les fonctions, parce que c'est plus logique d'ajouter une fonction et des droits (une fonction sans droits ça sert à rien). A voir

**Comment by nuffer** [comment]
Je suis entrain de m'occuper de restrucuturé toute la partie Structure/Hierarchie.  et je me disais que c'est surtout depuis la que tu gere ton groupe scout et depuis l'onglet sécurité que l'admin gere son site web...?!
