### ISSUE TITLE
problème avec le rendu de la liste Interne\FinancesBundle\Utils\ListModels\ListModelsCreances

### ISSUE THREAD

**Issue by nuffer** [sysmoh/intranetBS#64]
@ozwin J'ai un soucis avec le rendu de la liste en question.

Exemple concret sur la page de recherche de créance...j'ai des résultats (via dump) mais ils ne s'affichent pas dans la liste...bug??

**Comment by ozwin** [comment]
T'arrive à me linker les fichiers/lignes en question stp ?

**Comment by nuffer** [comment]
Même url que dans le titre de l’issue

Nicolas Uffer
+41 79/507.62.48
nicolas.uffer@gmail.com

**Comment by ozwin** [comment]
Ah ouais :D

Je vois pas le problème, t'es sur que ta liste en input est ok ?

**Comment by nuffer** [comment]
ben oui…mon dump sur la page de recherche de créance me donne bien une liste de créance…

Nicolas Uffer
+41 79/507.62.48
nicolas.uffer@gmail.com

**Comment by ozwin** [comment]
Le 2eme param c'est le router, il était manquant. Du coup t'avais le routeur dans la liste à la place des items.

J?ai fait les corrections, je te laisse clean les anciennes listes.

**Comment by nuffer** [comment]
top merci!!!!
