### ISSUE TITLE
App config

### ISSUE THREAD

**Issue by sysmoh** [sysmoh/intranetBS#70]
En faisant un fresh install j'ai vu que tous les paramètres généraux se trouvaient dans parameters.yml (et dans parameters.yml.dist). Il faut les bouger dans le fichier de config générale : app/config.yml

**Comment by nuffer** [comment]
yep! Tu tiens ca d'ou? nouvelle bonne pratique pour SF3? 

Ce que je vois en tout cas c'est que dans parameter.yml y a du merdier de "intranet_parameter" qui a normalement rien a faire la mais plutôt dans "appbundle/resource/config/intranet_parameter.yml"...Je peux m'occuper de cleaner ca à l'occas.

**Comment by nuffer** [comment]
c'est fait!
