### ISSUE TITLE
Optimisation

### ISSUE THREAD

**Issue by sysmoh** [sysmoh/intranetBS#72]
L'optimisation des templates twig se fait désormais grâce à l'utilisation du nouveau tag : 
`{% cache 'CLE_DU_CACHE' {time: 300} %} ... {% endcache %}`. Le paramètre time est obligatoire mais pour l'instant il sert à rien, le service qui s'occupe du cache est encore relativement basique mais ça viendra ! Il faudrait donc en mettre là où c'est nécessaire (on est déjà passé de 13 à 1 seconde de rendu pour la page d'accueil) !!

Cependant la grosse optimisation à faire est du côté d'assetic, en effet le problème est qu'en mode dev il faut charger plus de 20 fichiers css et js, et pour qu'assetic les renvoies c'est à chaque fois un processus TRÈS LOURD par fichier. La solution, en tout cas pour l'instant, c'est d'activer `debug: false` pour assetic dans config.yml, et de faire un `php app/console assetic:dump`.

**Comment by nuffer** [comment]
@sysmoh Y a-t-il encore des grand chantier à faire dans l'optimisation?

**Comment by ozwin** [comment]
On a viré assetics. Les perfs on bien progressé mais à mon avis c'est perfectible. Je ferme parce qu'il n'y a plus de suivi utile ici. Si la page met 3s à se charger, on risque pas de l'oublier ;-)
