### ISSUE TITLE
Créer un système de listes avec actions universel

### ISSUE THREAD

**Issue by ozwin** [sysmoh/intranetBS#9]

**Comment by nuffer** [comment]
Alors j'ai crée une exemple de liste universe pour mon Bundle (Finances/...recources/Templates/liste). 

il y a un exemple sur : .....web/app_dev.php/interne/finances/dev

Comme vous pouvez le voir ci-dessous, j'ai mis en place une system de parametrage de la liste à crée avant d'appeler la macro. 

Header = des label de colonne
Colomns = le nom de l'attribut à afficher
actions = la liste des actions dispo pour chaque entrée de la table
patternes = permet de lié une colonne à un affichage personnalisé en fonction de critère.
filters = des filtres que l'on peut lié à une colonne

Voila une petit exemple de code: 

{% set headers = [['','','Montants','','',''],['Num. Réf','Statut','Créances','Rappels','Total','Reçu']]%}

{% set columns = ['id','statut','montantEmisCreances','montantEmisRappels','montantEmis','montantRecu'] %}

{% set actions = [['voir','Afficher','voir_facture'],['delete','Supprimer','delete_facture']] %}

{% set patterns = [
                {'statut':'<div class="ui label green">Payée</div>','equal':'payee'},
                {'id':'N°[data]'}
                                ] %}

{% set filters = [
                {'montantEmis':'number_2'},
                {'montantEmisCreances':'number_2'},
                {'montantEmisRappels':'number_2'},
                {'montantRecu':'number_2'},
            ] %}

{% if ownerEntity.factures is not empty %}
{{ macro.liste(ownerEntity.factures,headers,columns,actions,patterns,filters) }}
{% endif %}

**Comment by ozwin** [comment]
Je fusionnerai les headers dans les colonnes, qu'on puisse les déclarer comme ça : 
> {% set columns = [
>     ['id', 'Num ref.'],
>     ['statut', 'Statut'],
>     ['montantEmisCreances', 'Créances']
> ] %}

**Comment by nuffer** [comment]
Oui et non ! :-) je vais voir mais les header ne sont pas forcement associé à une colonne (header de premier niveau)....

Sinon t'en pense quoi?

**Comment by nuffer** [comment]
Yep!

si jamais je vais bientôt push du lourd avec ma liste custum. J'ai ajouter un couche js et du coup ca sera mega facile de faire des actions en masse et aussi de s'apporché d'un équivalent datatable :-)
